#+TITLE: Where are the micro-worlds?
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{natbib}

# this is a comment, btw, I use org mode.
# Opassen dat het niet te historisch word
# Goed aankleden, kan een micro wereld worden gebruikt
# om een AI te ontwikkelen?

# Don't get lost in the technicalities.

# There are few recent publications about micro worlds, they used to be very
# popular in the 70's. Why aren't there anymore publications about this?

* What is a micro-world?
# my fellow students often don't understand what I'm talking about with just
# a "micro-world" so I should define well what I mean with it.

In a strongly recommended book cite:book_copeland,
the authors explained that in the 1970's there used to be programs that could
manipulate their environment based on language commands.

The term /micro-world/ was coined in an internal MIT memo in 1970 cited quoted
in cite:dreyfus1981micro: "Each model - or `micro-world' as we shall call it - 
is very schematic; it talks about a fairyland in which things are so simplified 
that almost every statement about them would be literally false if asserted about 
in the real world."

One of the first was called Shrdlu, invented by Terry Winograd.
This program controlled a robotic arm that could move blocks from one place
to another.

It could also understand natural language to an impressive level, as long 
as you were talking about stuff related to blocks.

# find a micro world definition in the papers
However the blocks and the robotic arm were virtual.

* Criticism on the micro-world approach
Here we'll discuss criticism on the micro-world approach with help of cite:dreyfus1981micro 
and cite:winograd1974.

* Could a micro-world be use-full?
Here we'll discuss how cite:honing1993microworld used a microworld in their
research and how they suggest.
(They suggest a micro world could be use full as an experimentation device).

* How complex does a micro-world need to be for AI?
This will be a small speculative chapter.
In here we'll explore the possibility of using a micro world as an AGI petri-dish.
This is done firstly by establishing that humans are an GI.
Then we'll establish that time in the micro world does not have to move at the
same rate as in real life.
Then we'll discuss the update rate of human senses.
Finally we'll introduce the micro-world/agent based architecture. (basically
agents that can only receive input trough senses and output trough muscle
control).

# Perhaps build on this and add my own thought experiments
# Build on this with good reasoning, don't trhow out random claims.

* Conclusion
We'll conclude that the micro world idea for language processing may not have
been the greatest but it can have uses as a research methodology.

<<bibliography link>>

bibliographystyle:unsrt
bibliography:refs.bib
