#+TITLE: Where are the micro-worlds?
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{natbib}

# this is a comment, btw, I use org mode.
# Opassen dat het niet te historisch word
# Goed aankleden, kan een micro wereld worden gebruikt
# om een AI te ontwikkelen?

# Don't get lost in the technicalities.

# There are few recent publications about micro worlds, they used to be very
# popular in the 70's. Why aren't there anymore publications about this?

In the early days of AI there was an idea of AI development called
"micro worlds".
A strongly recommended book cite:book_copeland,
the authors explained that in the 1970's there used to be programs that could                                                          
manipulate their environment based on language commands.
Something which even today quite novel with technologies such as Siri or
Google now.
Could you imagine how impressive this must have been in the 1970's?
The program called Shrdlu cite:winograd1971procedures 
and other areas such as computer vision cite:waltz1971.
All these results had one thing in common, micro worlds.
But in the last 20 years or so no more papers have appeared about micro worlds.
What happened to this approach?
Why did people stop doing research into it?
In this paper we'll explore firstly what the micro world is,
then we'll look at some of the criticism that probably let to its eventual demise,
with that criticism in mind we'll try to explore some possible use cases.

* What is a micro-world?
One of the first was called Shrdlu, invented by Terry Winograd cite:winograd1971procedures.    
This program controlled a robotic arm that could move blocks from one place                                                            
to another. 
However the blocks and the robotic arm were virtual.
The purpose of the program was to understand natural language, and it did
this very well.
It could for example deduce what reference words meant such as "it",
do semantical deduction (can the table pick up blocks?)
and understand concepts such as ownership.

The term /micro-world/ was coined in an internal MIT memo in 1970 cited quoted                                                         
in cite:dreyfus1981micro: "Each model - or `micro-world' as we shall call it -                                                         
is very schematic; it talks about a fairyland in which things are so simplified                                                        
that almost every statement about them would be literally false if asserted about                                                      
in the real world."                                                
Now this definition may already shed some light on the possible criticisms
on micro worlds, but we'll discuss that more thoroughly later.
It should be noted that this definition came from an internal memo in MIT
never meant for publication,
but since its fairly colorful we think it works very well.

A micro world is a sort of simulation, but we think its important to remember
the later part of the memo in which we say that things represented in a
micro world don't necessarily need to be true in the real world. A simulation
wants to try to be as close to the real world as possible
cite:wiki_simulation.

The difference between expert system and micro worlds is that
expert systems may have an internal simulation of the world,
but this isn't a micro world.
Micro worlds may not map directly to the real world but simulations
do want to do this.

A micro world is an artificially constructed world for conducting AI research.
The AI program (or agent) experiences the world trough senses to avoid logical
omniscience.
There is strict separation between world objects, and agent's believes.
Information has to pass trough senses to reach the agent.
It has an internal deliberation system separate of the world.
The AI program usually has a way to interact with the micro world, in case
of Shrdlu it was a robot arm.

                                                                   
* Criticism on the micro-world approach
Here we'll discuss criticism on the micro-world approach with help of Dreyfus
cite:dreyfus1981micro and Wingorad cite:winograd1974.

As always lets start with Shrdlu, why didn't this became the core technology
of Siri or Google Now? Well first of all Wingorad gave up devlopment in 1974.
He stated that developing the system just became to complex. He proposes
two potential ways of dealing with this,
create better abstractions and do things in a more modular way,
the second was a description of something which we today would call machine learning:
"The dream is that we can start with a minimum of structure, 
then provide masses of data and expect the program to build its own 
complexities" cite:winograd1974 (end of page 13).
He continues about wanting to have a type system (in paragraph 1.2),
without mentioning it (but all those problems would basically be solved with a
type system).
Lisp is dynamically typed. So why didn't he use a better language? There 
wasn't anything else, C was just invented.
A year before that ML (which had the desire winograd craved for without knowing
it),
but a year is not a long time for language adoption,
especially without the internet.

Dreyfus goes attacks Shrdlu from a different direction. He says that the
biggest issue not only Shrdlu had but all micro worlds was there limited
domain in the first place.
Take for example the concept of owning.
In Shrdlu's mind just a flag is set whether an object is owned by someone.
When later inquired about it he will just check the flag.
Therefore we can safely say that Shrdlu does not really understand what
it means to own something.
This argument is therefore a subclass of the syntax vs semantics discussion
which is out of the scope of this paper.

Another important thing to note is that Shrdlu uses a primitive to "understand"
ownership.
Wingorad thought that the size of the list of primitives would not be a
problem.
The use of primitives however flows eventually over into the frame problem.
Because you need to keep adding primitives to understand more of the world.
Initially wingrorad thought this list would be finite and better abstractions
could help with this.


So here we have an AI researcher giving up on the micro world because it became
to complex to work with, and then a philosopher stating that the micro world
approach is obviously not complex enough.

* Could a micro-world be use-full?
Here we'll discuss how cite:honing1993microworld used a microworld in their
research and how they suggest.
(They suggest a micro world could be use full as an experimentation device).

Often we have ethical dilemmas that don't make any real world sense,
but are still useful for the sake of ethics.
With micro world we can model these
because micro worlds don't have to make any real world sense, just internal sense.

In robotics code needs to be tested with expensive parts.
Using micro worlds which are free to copy we can cheapen the
development of robotic agents.

* How complex does a micro-world need to be for AI?
# we can also spin this as a prediction engine, ie the imagination of an agent
This will be a small speculative chapter.
In here we'll explore the possibility of using a micro world as an AGI petri-dish.
This is done firstly by establishing that humans are an GI.
Then we'll establish that time in the micro world does not have to move at the
same rate as in real life.
Then we'll discuss the update rate of human senses.
Finally we'll introduce the micro-world/agent based architecture. (basically
agents that can only receive input trough senses and output trough muscle
control).

# Perhaps build on this and add my own thought experiments
# Build on this with good reasoning, don't trhow out random claims.

* Conclusion
We'll conclude that the micro world idea for language processing may not have
been the greatest but it can have uses as a research methodology.

<<bibliography link>>

bibliographystyle:unsrt
bibliography:refs.bib
