#+TITLE: Summarizing evolutionary game theory
#+OPTIONS: toc:nil

In an evolutionary game, players are interpreted as populations. The
probabilities in a mixed strategy of a player in a bimatrix game are
interpreted as shares of the population. Individuals within the same part of
the population play the same pure strategy.
The main ‘solution’ concept is the concept of an evolutionary stable strategy.

The /Hawk-Dove/ game is a famous evolutionary game example:

|      | Hawk | Dove |
| Hawk | 0,0  | 3,1  |
| Dove | 1,3  | 2,2  |

The payoffs reflect (Darwinian) fitness, the number of offspring.
A mixed strategy $p=(p_1, p_2)$ is naturally interpreted as expressing the population
shares of individuals characterized by the same type of behavior. We are particularly
interested in symmetric Nash equilibria, where players have the same strategy.

Let $G=(A,B)$ be an $m\times n \text{-bimatrix}$ game. Then $G$ is /symmetric/
if $m=n$ and $B=A^T$, where $A^T$ denotes the transpose of A. A Nash equilibrium
$(p^*, q^*)$ of $G$ is /symmetric/ if $p^* = q^*$. /Every symmetric bimatrix game G
has a symmetric Nash equilibrium/.

Let $G=(A,B)$ be a symmetric game. Because the game is symmetric its sufficient
to give payoff matrix $A$. When we talk about a symmetric game $A$ we mean
$G=(A,A^T)$. Let A be an $m \times m \text{-matrix}$. $\Delta^m$ denotes the set of mixed
strategies. A strategy $x \in \Delta^m$ is an /evolutionary stable strategy/ in $A$ if
for every strategy $y \in \Delta^m$, $y\neq x$, there exists some $\epsilon_y \in (0,1)$ such that
for all $\epsilon \in (0,\epsilon_y)$ we have

\[ xA(\epsilon y + (1 - \epsilon )x) > yA(\epsilon y + (1 - \epsilon )x) \]

Consider any small mutation $\epsilon y + (1-\epsilon)x$ of $x$. Above condition then states
that against such a small mutation the original strategy $x$ is better than the
/mutatant/ strategy $y$, this is an ESS $x$ interpretation. Evolutionary
stability is regarded as expressing stability of a population against mutations,
this has game-theoretic as well as dynamic consequences.

If $A$ is an $m \times m \text{-matrix}$ and $x \in \Delta^m$ is an ESS in $A$, then 
$(x,x) is a Nash equilibrium in $G=(A,A^T)$. This shows that evolutionary
stable strategies result in symmetric Nash equilibria.

If $A$ is an $m \times m\text{-matrix}$ and $x \in \Delta^m$ is an ESS in A then
$\forall y \in \Delta^m$ with $y\neq x$ we have:

\[xAx = yAx \Rightarrow xAy > yAy\]

Conversely, if (x,x) \in \Delta^m \times \Delta^m is a Nash equilibrium in $G=(A,A^t)$ and the
above condition holds, then $x$ is an ESS.

To find evolutionary stable strategies for an $m \times m$ matrix we first compute
the symmetric Nash equilibria of game $G=(A,B)$ with $B=A^T$. Each 
equilibrium $(x,x)$ where $xAx = yAx \Rightarrow xAy > yAy$ holds is an evolutionary stable
strategy.

This is the replicator dynamics of the Hawk-Dove game:

\[ \dot{x}(t) = dx(t)/dt = x(t) [3(1 - x(t)) - (2 - 2x(t)2)]\]

It says that the population of hawks changes continuously, and that this change
is proportional to the difference of the fitness at time $t$.

If $A$ is an $2 \times 2 \text{-matrix}$, then $A has at least one evolutionary stable
strategy, and $x=(x,1-x)$ is an evolutionary stable strategy of $A$. If and only
if $x$ is a stable rest point of the replicator dynamics. For general
$m \times m \text{-matrices}$ the set of completely mixed rest points of the replicator
dynamics coincides with the set of completely mixed (symmetric) Nash equilibrium
strategies. There are also connections between stability of rest points and further
properties of Nash equilibria.

In a $2 \times 2$ bimatrix game a pair of strategies is a stable rest point of the
replicator dynamics if, and only if, it is a strict Nash equilibrium. For
larger games, any stable rest point of replicator dynamics is a strict Nash 
equilibrium but the converse does not necessarily hold.

* Questions

1. What are some applications of evolutionary games?
2. How is evolutionary game theory connected to multi-agent learning learning?
