#+TITLE: questions

* Dignum

** Email
Beste dr. Dignum,

Bij deze een kleine status update.

Het test scenario is inmeddels geimplementeerd en de tests slagen.
Tijdens het uitvoeren waren er wel enkele vrij serieuse fouten tevoorschijn
gekomen die in het thesis worden besproken.

Het volgende wat op de planning staat is het AIML naar YAML script.
Maar ik zou ook extra experimenten kunnen gaan uitvoeren en daarop
reflecteren.
Mogelijkheden tot experimentatie:
  + Het effect van de 'lagere functies', zijn lagere functies uberhaupt nodig?
  + Volgorde van de top level functies: heeft het zin? Wanneer wel wanneer niet?

* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)


** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
** Conversation notes <2017-03-23 do> 

He seemed overall quite happy with the result. Probably a little to big to fast.
Validate work with qualitative tests?
Possible social practice integration with personality in the thesis?
+ For example its context isn't taken in consideration.
+ You could counter this by saying that we can wrap the jungian function inside
  a context care taking function.
I don't use BDI because there aren't any RETE engines so you can't use logics
on that?
+ But isn't this countered by the fact the believes get inserted each time a
  function is called?
+ Perhaps I should discuss this also in the thesis
