#+TITLE: questions

* Dignum

** Script
1. Start server
2. zet persoonlijkheid die in believes.yml op INTJ
3. Build
4. Open test gedeelte van thesis
5. Open Unity client en ga INTJ test af
6. Voor ENFP moeten we python gebruiken omdat Unity client niet uttrences achter
   elkaar kan laten zien.
7. ISTP ook python.
8. Eventueel ook nog over convert.py

** Vragen
Ik weet nu niet even wat het belangrijkst is om eerst te doen,
thesis afmaken,
implemantatie verbeteren van persoonlijkheid,
implementatie verbeteren van AIML features.
Ik dacht zelf thesis afmaken, en dan als er tijd over is 1 van de implementatie
mogelijkheden.

* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)


** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
** Conversation notes <2017-03-23 do> 

He seemed overall quite happy with the result. Probably a little to big to fast.
Validate work with qualitative tests?
Possible social practice integration with personality in the thesis?
+ For example its context isn't taken in consideration.
+ You could counter this by saying that we can wrap the jungian function inside
  a context care taking function.
I don't use BDI because there aren't any RETE engines so you can't use logics
on that?
+ But isn't this countered by the fact the believes get inserted each time a
  function is called?
+ Perhaps I should discuss this also in the thesis
