#+TITLE: questions

Should I treat UML in the background section?
Because I use that for most diagrams.

Should I add more diagrams to BDI & Jung? I sortoff don't know about what more to make it?

I didn't add an overview in chapter 3 because it didn't fit in there because its
to detailed for that chapter.
I pushed it down to a new chapter instead, is this OK?

Should I refer to a design practices book (I was thinking head first design patterns)? I mean I do most stuff by heart but
I'm pretty sure all the stuff I do is written somewhere..
 Could be in Qaulity attributes?
 Could be in head first design patterns?


* Manuel

** Knowledge representation
1. Currently drools can't reason on possible responses since there are no
   connections encoded anywhere.
2. The perlocutionary respones (emotions etc) should be encoded somewhere
  (currenty in rules I believe? Maybe can do this with reflection)

** Architecture
Dignum wants to be able to run multiple agents.
So perhaps clustering emotions and personality into 1 kie session and
another kie session for scenario progression and score.

However he also said that maybe even scenario progression should be part of each
agent, as in they believe they are something while they're not??
Seems rather complicated to me.
He also talked about score for each agent? But I thought that if the score
drools can just have read access to all the facts they can keep track
of it as just a single instance.
*** Details
1. Drools can't use predifined AIML responeses so they have to be encoded inside
   the drools themselves as strings which is rather messy
2. Predicates is unsynchronized and since in thoery drools should be able to be
   ran in parrelel, this could cuase future problems, why aren't these just
   inserted as facts?

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)
