#+TITLE: questions

* Dignum

** Status
+ Twee weken geleden functies af gemaakt. (tenminste zover de unit tests aangeven)
+ Gister en eergister documentatie weer wat op peil gebracht.
+ Vandaag en morgen beginnen met het integratie test scenario opzetten.

** Vragen
Hoe gelijk moet ik de notatie houden met wat er in de code staat?
DialogueTree gebruikt heeft bijvoorbeeld nu wat meer informatie beschikbaar als
beschreven in BDI+Jung.

Volgens mij heb ik de problemen inmidels opgelost voor het maken van een $n$-agent
architectuur, maar volgens mij is het nog steeds in beter idee om eerst alle
andere dingen op de todo lijst af te maken.

* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)



** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
