#+TITLE: questions

* Dignum

** Email
Beste dr. Dignum,

Bij deze een kleine status update.

Daarna bezig gegaan met het implementeren van een test scenario die ik tegen dinsdag kon uitvoeren.
Hieruit waren enkele fouten voortgekomen:

1. Low level replies waren nog niet geïmplementeerd (voornamelijk voor hallo -> hallo reacties).
2. Er was altijd maar 1 "symbool" reactie, zelfs als de persoonlijkheid dacht dat er 2 dingen achter elkaar gezegd konden worden.
3. De hoogte waarop functies zouden moeten werken was niet goed uitgewerkt.

Punt 1 en 2 zijn inmiddels klaar. Als punt 3 af is ben ik van plan nog een integratie test te doen, punt 3 is verrassend complex om goed te doen en heeft zelfs gezorgd voor een uitbreiding in BDI+Jung.

De dag nadat ons gesprek had ik geskyped met manuel. Sindsdien heb ik enkele emails naar hem gestuurd maar alsnog niks van hem gehoord.
Het probleem waar ik tegen aanliep is dat er 2 dubbele implementaties zijn en hoe ik deze het best kan verenigen (tussen social practice in drools en een java class die ik had geschreven).

* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)


** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
** Conversation notes <2017-03-23 do> 

He seemed overall quite happy with the result. Probably a little to big to fast.
Validate work with qualitative tests?
Possible social practice integration with personality in the thesis?
+ For example its context isn't taken in consideration.
+ You could counter this by saying that we can wrap the jungian function inside
  a context care taking function.
I don't use BDI because there aren't any RETE engines so you can't use logics
on that?
+ But isn't this countered by the fact the believes get inserted each time a
  function is called?
+ Perhaps I should discuss this also in the thesis
