#+TITLE: questions

* Dignum

1. Wat moet ik precies doen om het makkelijk te maken voor een andere student?
   1. Er is al een build guide, dus in princiep zou het vrij makkelijk moeten
      zijn voor een andere student om het over te nemen.
      Deze bouw gids gaat uit van linux (ubuntu of gentoo)
      omdat package managment instalatie stukken makkelijker maakt.
      Je moet bijvoorbeel mariadb (mysql) instaleren en maven instaleren
      Wat niet triviaal is.
      Daarnaast word de commandline gebruikt om deze software te gebruiken.
      Ik weet niet hoe derglijke dingen op windows gaan.
      Maar gellukig is ubuntu gratis en makkelijk te instaleren.
   2. De bot is in princiepe niet afhankelijk van mariadb, mysql of maven.
      Ik zou een variant kunnen maken die deze afhankelijkheden niet langer heeft.
      Ik had het destijds zo gedaan omdat er een client server achtectuur is.
      Wat ik dan doe is de bot opzetten als een library.
   3. Mischien is het beste dan nog wel dit te overleggen met manuel?
      Zodat die het aan een andere student kan uitleggen?
      Ik dacht dat manuel het ook zo deployde...
      Maar volgens mij had hij ook een applicatie ofzo gemaakt om te testen.
      Het probleem was dat deze niet bij mij werkte omdat javaFX werd gebruikt.
2. Kan ik de code opensourcen?
   1. Bijvoorbeeld met LGPL, zelfde licentie als de ALICE bot.
   2. Moet ik ook overleggen met Manuel..

* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Questions
1. Are you familiar with unity to make it show multiple ansers or just the awnser log?

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)


** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
** Conversation notes <2017-03-23 do> 

He seemed overall quite happy with the result. Probably a little to big to fast.
Validate work with qualitative tests?
Possible social practice integration with personality in the thesis?
+ For example its context isn't taken in consideration.
+ You could counter this by saying that we can wrap the jungian function inside
  a context care taking function.
I don't use BDI because there aren't any RETE engines so you can't use logics
on that?
+ But isn't this countered by the fact the believes get inserted each time a
  function is called?
+ Perhaps I should discuss this also in the thesis
