#+TITLE: questions

* Dignum

  Het lijkt erop dat Manuel privé problemen heeft op het moment dus ik heb hem
  niet echt kunnen updaten van recente ontwikkelingen.
  Dus ik weet niet of hij het eens is met de manier waarop ik het
  persoonlijkheids proces heb geïmplementeerd.
  Ik ben verder gegaan met het implementeren van functies en het schrijven van
  unit tests voor deze functies.
  De functies die nog missen zijn Ti en Ne, ik weet vrij zeker dat ik deze
  functies deze week nog af zou kunnen krijgen.

  Als dit af is ga ik denk ik beginnen met integratie tests.
  Dit zou handmatig of automatisch kunnen gebeuren (ie maak een persoonlijkheid
  aan in junit & kijk of het de juiste reacties geeft).
  
  Wanneer dat af is ga ik denk ik grondig beginnen met het op peil brengen van
  het thesis. (wat ik vandaag dus ook al in redelijke mate heb proberen te doen 

  ---

  Over het PhD aanbod, ik ben aan het twijfelen over het aanbod.
  Er zijn hier enkele redenen voor,
  ten eerste is het termijn van zes jaar is wel erg lang
  en ik weet niet zeker of ik zo lang gemotiveerd kan blijven over een enkel
  onderwerp, daarnaast word dit versterkt door de onzekerheid of het wel
  praktisch wat oplevert.
  Om een juiste keus te maken zou ik toch meer willen weten over de opdracht:
  + De werkplek
    + Waar is het.
    + Kan ik op afstand werken voor lange periodes (denk enkele maanden).
  + Vooral voor p-direkt:
    + Precieze inhoud van het werk.
    + Softwarestack, ik zou hier het liefst vrije keuze in hebben
      (denk bijvoorbeeld aan editor en OS keuze).
  + Het uiteindelijke loon

* Manuel

How about social practices?
+ Should an exact order be imposed?

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)



** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
