#+TITLE: questions

* Dignum

I should prepare a demo for next meeting if I can
I should make sure to update thesis to recent code base so he can see what I'm
doing.

* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)


