#+TITLE: questions

* Dignum
Beste dr. Dignum,

Hierbij mijn werk van deze week,
Ik denk dat ik al uw aanmerking heb verbeterd:
+ Spelfouten nagelopen (en een spellchecker over het hele document gedaan).
+ Introductie fouten verbeterd.
+ Social practice
  + Plan patterns verbetered waar nodig
  + Introductie toegevoegd
  + Figuur 1 veranderd naar state diagram (heeft geen beslissings punten,
    dus geeft alleen mogelijke transities aan, wat volgens mij neerkomt op
    tijdvolgorde)
+ Related work hoofdstuk naar achter achtergrond hoofdstuk verplaatst
+ Personality case studies is verplaatst naar implementation hoofdstuk

Bij hoofdstuk 2.2 stond een notatie dat ik beter IVA kon gebruiken
(als basis),
ik neem aan dat dit stond voor interactive virtual environments.
Ik heb hier een subkopje voor toegevoegd maar weet niet echt verder wat met dat
comentaar werd bedoeld

> Wat ik ergens in de laatste hoofdstukken wil zien is een doorlopen van de
  scenario's en dan aangeven wat er nu intern gebeurt zodat duidelijk is waar
  de persoonlijkheid invloed heeft en waar dat zichtbaar is.
  In de appendix zeg je wel dat er iets uitkomt maar niet hoe. 

Dit is gedaan in het implemenatie hoodstuk, in sectie "making the scenario"
Specifiek de subsecties "Believes" en "steering the bot".
Ik had er aan gedacht om dit nog specifieker te maken,
maar dan word het broncode bij langs lopen.
Wat opzich wel te doen is aangezien het persoonlijkheid specifieke gedeelte
mischien 200 regels java code in totaal is exclusief commentaar
(wat het aantal verdubbeld).
Maar omdat u zij dat broncode geen centrale rol speelt heb ik hier tegen besloten.

Ik vroeg me af welke figuren naar de appendix verplaatst horen te worden,
alle, of alle grote? en of dit inclusief tabellen, listings en formules is.

Bijgevoegd thesis in huidige staat,

Mvg,

Jappie Klooster


* Manuel

  Probablistic generation of next dialogue moves could be combined with moddeling one
  of the Jungian Irrational functions??

** Questions
1. Are you familiar with unity to make it show multiple ansers or just the awnser log?

** Conversation notes <2017-01-30 Mon> 

*** Thesis
 where is Bdi + jung used?
    Perhaps I should add a diagram or discuss this explicitely, where the social
    contexts operates and where the personality operates

 Is there Bdi research for dialogue navigation?

*** Architecture 
 social practice and agent should be distinct

*** Meaning handling
 probelastic matching o meanings??
 probablistic model for the m graph??

 dynamic generation of responses with owl?

 link utt & resp w drools? <-- this will be done by Miguel 


*** Other
 information state approach = belief.

 action = what happened?

 we want a language that can describe sp. (I mean I don't have to work on this right?)


** Conversation notes <2017-02-15 wo>

Move process personality to drools. In a drools personality package.
(perhaps meanwhile move patternmatching into chatbotengineimpl)
Move to the master branch.
Move pattern matching in drools. 
** Conversation notes <2017-03-23 do> 

He seemed overall quite happy with the result. Probably a little to big to fast.
Validate work with qualitative tests?
Possible social practice integration with personality in the thesis?
+ For example its context isn't taken in consideration.
+ You could counter this by saying that we can wrap the jungian function inside
  a context care taking function.
I don't use BDI because there aren't any RETE engines so you can't use logics
on that?
+ But isn't this countered by the fact the believes get inserted each time a
  function is called?
+ Perhaps I should discuss this also in the thesis
