* first meeting
Voeg personlijkeid toe aan een patient communicatie game.
moet makkelijk aan verscillende charecters worden veranderd.

Papers lezen.
- Wat heb ik begrepen
- Wat ga ik doen
Op basis hiervan een planning maken
education pagina fomulier invllen.

Voor 11 november af hebben gemaakt.

* Paper campos_ mabs 2009

** Personality
*** Content oriented
    Assign values to relationships between agent personality, the situation, and
    the possible actions.
    This lacks flexibility since different siutations require different values.
    # also its opaque in my opinion
*** Process orientated
    Agents prefer a particular process
    # so could this mean preference to being treated polityly/directly
    # in communication? How do you distinguish such a preference in text?
    # How would you give this feedback in a game.
    its mbti...
    # damn, my old nemisis returns, well this becomes easy...

    # Wait why are I/E and J/P ignored, they're like super important, especially
    # for planning (well J/P are)...

** Fictisious personality
    In Weide et al, (Personality based practical reasoning 2008) the agent reasons
    about te users personality. may be interesting.

** Comments
*** How to change planning into dialogue?
  Perhaps the scanerios have goals or someting, and agents/patients can choose
  certain rections to achieve those goals. Then we can inject personality in there.

*** TODO get MBTI definitions straight
Is MBTI even types? I think the test gives you scores anyway just like the trait
pshycology does. Not to speak about [[http://thoughtcatalog.com/heidi-priebe/2015/06/if-youre-confused-about-your-myers-briggs-personality-type-read-this-an-intro-to-cognitive-functions/][Cognitvie functions.]] 
So I want to recheck those referecnes and make sure the things described in the
paper are correct (since I remember it somewhat different).
Anyway I think even its not interperted quite right the main idea of the paper
still will work.
Perhaps I should ask about this?
Can I use please understand me II as a source?

Should acknowledge the critcism on MBTI and give a reply (types are easier
than floating points).
# So maybe this is overkill?
*** TODO look closer at that logic

* Paper AngelloGala 2015

paramters for dialogue state.
Nodes are player statements and computer statements. (is that s right?)
interleaves in which one or more conversation trees can take place???

Structuaral dialoge state approach.

scanerio parameters are emotion scores (there are 7, but  what do they entail?)
and the last computer statement (dialoge tree position I presume).

Dialoge "moves" are selected for the player based on scanerio parameters.

** TODO How to map dialogue onto a goal driven system?
Is dialogue a process?
How do different types preference go regarding dialogue?

What is the standard conversational protocol?

** MBTI
Is there research concerning how types of personalities interact with each
other?
What effects does MBTI have on norms?

** Arhcitecture
   This thing has to many arrows, everything points to everything, can't this
be simplified?

Context = theory of social practice

*** flow
1. Observe the context and update beliefs and goals
  (this is weird, since no delibiration has happened yet, how do you you know what to change)
2. Activate a set of possible social practices
3. The most appropiate is selected by an internal reasoning process
4. With that delibarte how to manage the conversation within context of practice
   1. If there is not enough information, interaction with the user occurs

*** Model of social practice
I think its important to ask yourself in this chapter, how much can be left
implicit? Is this here for toroughness (theory) or are you going to define per
scenario "norms: doctor is polite, patient cooperative."

* Questions

** How far is agentification of communicate! implemented?
