#+TITLE: Process
# Pure functional serious comminucation in-game
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \renewcommand{\bibsection}{}
#+LATEX_HEADER: \usepackage[obeyFinal, colorinlistoftodos]{todonotes}
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper, drafting]
#+Options: toc:nil ^:nil 
#+Options: title:nil
#+LATEX_HEADER: \newcommand{\drafting}{\todo[noline, color=gray]{Working draft}}
#+LATEX_HEADER: \newcommand{\toReview}{\todo[noline, color=yellow]{To review}}
#+LATEX_HEADER: \newcommand{\underReview}[1]{\todo[noline, color=olive]{Under review by #1}}
#+LATEX_HEADER: \newcommand{\cleared}{\todo[noline, color=white]{Cleared}}

# Title page
#+LATEX: \input{title}

# The order of this thesis will be done in a way to let future researcher
# decide the value of the thesis quickly
# 1. First the abstract to let a researcher quickly discard this thesis if neccesary.
# 2. The toc, to let a researcher jump to interseting pages quickly.
# 3. The introduction and main body of the thesis. If all else fails a
# reaserhcer can use this as fallback

* Tools used
This thesis was written in spacemacs with help of org-mode.
The program changes were also made with spacemacs.
Version control was done with help of git.
*** Finding references
Most references were found with help of Google scholar,
To get papers either to verify them for reliability or to check theory
the first attempt was usually the [[http://scholar.google.com.proxy.library.uu.nl/][university proxy]].
This sometimes failed, especially for older or more niche papers,
which resulted in the use of [[https://moscow.sci-hub.ac/][sci-hub]].
Sci hub significantly helped in the verification of sources.

Once a copy of the paper was aquired I could see what the basis was of the
reference.
Many authors acutually don't cite a source but rather someone else
talking about a source.
I think that's ok, but to get more information you can try to find that paper
too.
The abstract is extremely use full in determining if you should consider the
paper or not.

Books were much more problematic to come by however.
Especially older books, I couldn't find for example "gifts differing" or
"psycologiese typen" anywhere except as hard copies which would take to long and
for which I don't have the money.
Isn't it strange that at least 35 years after their dead Meyer-Brigs and
Jung still earn money?
I eventually found a primer jungian psycology cite:hall1973primer, in an
online library from which you could "borrow" the book.
Which basically meant either an encrypted file or view it in the browser.
This resulted in making screen shots of the book since I wasn't in the mood
to reload the website every time I needed to look up some detail.
Other methods I used included [[http://gen.lib.rus.ec/][library genises]], and [[https://www.reddit.com/r/Piracy/comments/2oftbu/guide_the_idiot_proof_guide_to_downloading_ebooks/][irc book downloading]].
I never found a good book on MBTI, and had to result on papers describing it or
websites.


* Complaints
Lets talk about this paper cite:jennings2001agent.
I like how they compared agents to objects completly ignoring that 
agents are a subclass of objects, and provide a reference to a guy that
said classes and objects don't provide enough abstraction, yes you idiot,
YOU ARE SUPPOSED TO PROVIDE THE ABSTRACTION
Then they go on proposing how every agent should have an own thread of controll
to make modeling the domain easier...
are you shitting me? You want to introduce /more/ threads to make
things easier?!
The term complex system was never defined, this was handy for when they needed
some circular arguments such as: "however since the systems' ineherit complexity
it is impossible to know apraroi all possible interactions",
we have a solution for that, its called a type system and pattern matching.
Also note how the fact that designing systems can be "natural",
yes this is how I imagine my ancestors, trying to start a fire while talking
about composite banking.
The final remark is the use of images, the first image the system is all
squibaly and dark colours, wheras the second and third one are way more
organised and lighter in colour.
Noticing this I was like how popular is this thing,
its obviously trying to do unconsciousness manipulation: 1404 citations.
crap, my faith in humanity took another hit.

And yet I will hypocratly cite this paper do because it does what I need it to do,
argue in favor of bdi so that I can use the rest of my teacher work in
"good consciousness".
In a perfect word I would try to make a "critique" paper on this paper,
but this would significantly delay my study and I just don't care about this
particular design methodology that bad.
Now, PICK UP THAT CAN

* Problems with building
I extracted the unity game rather stupidly where the project was extracted,
and then also re-extracted within a subfolder causing a super weird project
structure and git in git repositories.

There was an unmerged meta file, these files probably shouldn't even be tracked
since they're auto generated.

There were references to the "unity" editor which caused build errors. I just
remoeved the references and it build fine ergo the references were redundant.
I think re-sharper could've fixed this.

gradle can't do wildfly

Maven for some reason needs to have a profile to allow it to compile?
So it needs to know my name? wut?

I downloaded the wrong application server that did not contain a datasource
subsystem, in doing so I spend over 2 days trying to enable mysql on a non
existing subsytem.
This wouldn't have been a problem if mvn wildfly:run would also include a
datasource subsystem, which it didn't.

To combat these issues I made a build guide and included it as an appendix
to the thesis (I don't want anyone else to deal with this crap).
