#+TITLE: A serious communication game with personalities
# Pure functional serious comminucation in-game
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \renewcommand{\bibsection}{}
#+LATEX_HEADER: \usepackage[obeyFinal, colorinlistoftodos]{todonotes}
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper, drafting]
#+Options: toc:nil ^:nil 
#+Options: title:nil
#+LATEX_HEADER: \newcommand{\drafting}{\todo[noline, color=gray]{Working draft}}
#+LATEX_HEADER: \newcommand{\toReview}{\todo[noline, color=yellow]{To review}}
#+LATEX_HEADER: \newcommand{\underReview}[1]{\todo[noline, color=olive]{Under review by #1}}
#+LATEX_HEADER: \newcommand{\cleared}{\todo[noline, color=white]{Cleared}}

# Title page
#+LATEX: \input{title}

# The order of this thesis will be done in a way to let future researcher
# decide the value of the thesis quickly
# 1. First the abstract to let a researcher quickly discard this thesis if neccesary.
# 2. The toc, to let a researcher jump to interseting pages quickly.
# 3. The introduction and main body of the thesis. If all else fails a
# reaserhcer can use this as fallback

* Abstract                                                          
:PROPERTIES:
:UNNUMBERED: t
:END:

#+BEGIN_CENTER

\todo[inline]{abstract}

#+END_CENTER
\todo{keywords}

\newpage
#+TOC: headlines 2

\newpage

\toReview
Communication is the foundation of our modern society.
Having good communication skills can help individuals in both professional as
their personal lives.
However training people in communication skills can be difficult.
Another party is required to communicate with,
and a tutor or teacher has to be there to give feedback.
Serious games can be used to train people with these kind of skills
cite:swartout2013virtual.
Therefore a general "communicate!" game was developed.
Wherein teachers can create scenarios to let students play it cite:jeuring2015demo.

\toReview
A script based game has of course the weakness that a student can't use
creative responses, all possible responses are scripted into the scenario
and replying correctly relies on a simple /abc/ choice.
To combat this the Weiderveld created an alternative serious game based on the
chatbot Alice cite:weiderveld2016chatbot.
This bot was however extended with the idea of social practices,
to both measure performance and limit the domain to that of a doctor appointment.
In this thesis we are interested in extending his work with personalities
on top of social practices.
Meaning that the patients will have personality.

\toReview
Since the personality topic has become quite popular in recent years will
first take a small chapter to look at related work.
After that, to validate our work according to personality research
we'll look at existing personality theories and their advantages and
disadvantages,
keeping practical considerations in mind.
Then we'll have a look at idiomatic AI programming and how in theory personality
could be combined with AI.
We continue by taking a close look at the state of the existing software we're
planning to extend.
After this we'll discuss the implementation.
Finally we'll compare the different implementations.

* Related work
\toReview
  To simulate personality in comminucation games there have been already several
works proposed.
Etheredge used the OCEAN personality theory to create argumentative
agents cite:etheredge2016personality.
Although argumentation is not the same as comminucation we can consider the
method used to make the personality.
In this paper a personality model is introduced based on OCEAN.
To move from personality values in OCEAN towards action selection fuzzy logic
is used.
However this has a major disadvantage in that a lot of rules need to be
added to do action selection.
This can make action selection opaque.
It is for example not immediately clear how a higher anxiety will influence
action selection.
Having a lot of rule also make maintenance hard, if for example there is an
unwanted behavior many rules need to be inspected before the change can be made.

In agents with with personalities cocu tried making a complete game based
on MBTI cite:cocu2015agents.
However comminucation was never implemented and personality got reduced to
doing a single action.

Van den bosch also chose to use OCEAN to model characters in a serious
comminucation game cite:van2012characters.
He used a nested probabilistic if else structure to decide on how agents should
interact.
His methodologies had some shortcomings however,
for example a not agreeable person was defined as someone who'd had a high
probability of telling facts about himself.
Which in certain situations could be considered strange,
for example a spy who was captured.
This kind of methodology is called content orientated cite:campos_mabs2009,
the personality, would and should change depending on context.

Campos used the MBTI to create BDI based agents cite:campos_mabs2009.
We will use a more fine grained version of MBTI but his architecture is used,
in which personality will be processed orientated rather than content
orientated.

* Personality theories
\cleared
The field of psychology has been somewhat active in trying to model human
personality cite:pervin2008handbook. 
Several frameworks have been developed to figure out people's
personality and what this in turn would mean for their lives.
We are interested in two ways in existing personality theories:
1. Accuracy, if a personality thoery does not fit the reality at all it won't
   help anyone in the serious game.
2. Ease of implementation. If the personality theory is too hard (or impossible)
   to implement in the serious game than we can't use it.
The field of psychology is very interested in the first requirement. 
However the second requirement not so much.
Therefore our first job will be to list existing psychology personality
frameworks,
and filter out those that are unfeasible to implement.


** The big five
\cleared
The first framework we'll discuss is called the big five.
The term big five first coined in 1981 by Goldberg cite:goldberg1981language.
The big five were not big because of their intrinsic greatness,
but rather to emphasize how broad these factors were.

\cleared
This framework was not really invented, but rather discovered trough
lexical analyses cite:tupes1961recurrent.
Although the labels used were different,
they conveyed the same idea as the big five model used now.
The methodology used is something which is called factor analyses[fn::
In the paper the term 'varimax rotational program' is used,
but if we look this term in wikipedia, we can see the result is called factor
analyses cite:varymaxrotanonalprogram].
Factor analyses is a statistical methodology that tries to find underlying
hidden variables.
This methodology has become widely used in psychology cite:fabrigar1999evaluating.

\cleared
In the begining of the 1990's there were many ways to measure personality that
didn't agree with each other.
For example at Berkley alone block used a 2 dimensional ego-resilience and
ego-control method cite:block1980role,
whereas Gough measured folk concepts such as self-control, well-being and
tolerance cite:gough1987california.
Personality researchers hoped that they would be the one to discover a structure
that would then be adopted by other researchers cite:pervin2008handbookp114.

\cleared
The goal of the big five was not to present a new structure that convinced
others to use it,
but rather to provide a taxonomy that all psychologist could agree upon.
Since the big five was so broad (because of the statistical methods used),
this worked.
Therefore the researchers could keep on exploring there niche with their
proffered structure,
but once they would present their work they could use the big five to
communicate clearly what their research meant without having to redefining the
words every time cite:pervin2008handbookp114..116.

\cleared
The big five as in the OCEAN definition has the following units of measurement:
- Openness or originality, if you score high on this you enjoy learning new
  things just for the sake of learning. If you score low then you don't enjoy
  this
- Conciseness, how tidy you are, if you score high the dishes don't stack up
  in the sink.
- Extroversion, a high score indicates you enjoy leading the conversation and
  you'll speak up when you disagree with someone.
- Agreeableness or altruism, a low score would indicate that you don't want to
  share and generally don't trust people.
- Neuroticism or nervousness, a high score indicates that you like to brag and
  get upset when someone is angry at them.

\cleared
The big five has been extensively tested and the result has been replicated
in multiple studies cite:pervin2008handbookp119.
One can measure his big five score trough a test called the NEO-PI, or the
NEO-FFI. The FFI variant is shorter but less precise cite:costa1992revised.

\cleared
Although these terms may provide a great taxonomy,
it does not have any theoretical foundation cite:eysenck1992four.
This means it becomes difficult to speak about implementation.
To make this more clear we use a thought experiment:
Lets say you have a score of 0.8 for Neuroticism,
how does this influence my decision for selecting action $a$ or $b$?
Now you could say, use a mixed strategy where in you choose 80% of the time
the neurotic typical neurotic approach.
Then we need a valuation function to decide which of the two actions is more
neurotic.
But once we've done this we still haven't taken into account any of the
other factors.
Solving this is a non-trivial endeavour.

** Personality types
\cleared
To address the big five's issue of having no thoeretical foundation we'll
have a look into personality types.
We begin with the theoretical foundation proposed by the grandfather of
personality research, Carl Jung.
After which we'll look at a thoeretical evolution proposed by Myers and
Myers-Brigs, which also introduced a structered method of measuring types.
Then we'll discuss some critique on this method.
With this critisim in mind we'll look at alternatives to the MBTI that have been
proposed afterwards.

*** Jung's theory of psychological types
\cleared
Jung describes several concepts, firstly each person has two attitudes:
/Introversion/ and /extroversion/.
Extroversion means dealing with the outside world and therfore is called
objective (or observable).
Intoversion is the world inside a person, and therefore is subjective,
or private.
This privacy however may bo so great that the consiouness can't even access it.
These attitudes are mutually exclusive,
you can't do introversion and extroversion at the same time.
For example if you're day dreaming you're not paying attention to your
surroundings.
A person who spends most of his time in the introversion attitude is called
an /introvert/.
But he is not totally the one or the other, ie an introvert can still have
extravert moments and vice versa.
It should also be noted that the unconsciousness according to Jung is
flipped in attitude. cite:hall1973primer97-98attitude

\cleared
Then there are four functions.
The first two functions are called the /rational functions/
because they act as a method of making judgements.
/Thinking/ is a function that connects ideas with each other to arrive at
generalizations or conclusions. 
/Feeling/ evaluates ideas by determinging if its good or bad, pleasant
or unpleasant, beautifull or ugly.
Note that this is /not/ the same as being emotional,
although you can be emotional and use this function.
The /irrational functions/ are called this becuase they require no reason.
/Sensation/ is sense perception created by the stimulation of the senses,
it can always be rooted to a sense,
such as "I see a balloon" or "I feel hungry".
/Intuition/ is like a sensetion but its not produced by a sense.
Therefore it has no origin in the same way as sensation has,
by which its explained as "just a hunch" or "I feel it in my bones".
cite:beauchamp2005communication,hall1973primer98-100functions

\cleared
To use these functions they have to be combined with attitudes, producing
/function attitudes/.
Therefore a person will never be of a thinking type,
but rather either a thinking introvert or thinking extrovert.
cite:hall1973primer100-101combo
We can now imagine what this means,
an extroverted thinker will for example make judgement about the real world,
and therefore be more like a scientist,
whereas an introverted thinker will make judgement about ideas in his mind,
and therfore will be an excelent philosopher.

\cleared
Let $\mathcal{J}$ denote the set of all possible jungian function attitudes
such that:
\[ \mathcal{J} = \{ T_e, T_i, F_e, F_i, S_e, S_i, N_e, N_i\}\]
Where
+ $T_e$ stands for extraverted thinking, which is thinking about objects in the
  real world. This is thinking with a goal, a problem to solve,
  to check weather certain laws are upheld, or a system to check.
+ $T_i$ stands for introverted thinking,
  this kind of thinking could be called deductive,
  it tries to construct a framework to explain the world.
  This is consistent reasoning based on internal believes,
  which does not necessarily solve a problem.
+ $F_e$ stands for extraverted feeling, where objective or external criteria
  is used to judge, for example something is beautifull or ugly.
  Established standards may be used to decide this and therefore its a
  conservative function. Decisions are based on interpersonal and cultural values.
+ $F_i$ stands for introverted feeling, decisions based on personal values and
  believes.
+ $S_e$ stands for extroverted sensing, Act on concrete data from the here and
  now. Then lets it go.
+ $S_i$ stands for introverted sensing, acts on concrete data from memories and
  passed experience.
+ $N_e$ stands for extraverted intuition, try to find possibilities in every
  situation.
+ $N_i$ stands for introverted intuition. Looks new possibilities in ideas.

\cleared
Another important concept is the idea of the /principal/ and /auxilirary/
function cite:hall1973primer105principal.
The principal function is the one that is most preffered.
The auxilirary renders its services to the principal function,
however this function cannot be the opposite of the principal.
So if /Feeling/ is the principal function than thinking connot be the auxilirary.
This is also true for the irrational functions.

*** MBTI
\cleared
The meyer brigs type indicator is based upon Carl Jung's theory of personality
types.
However it brings two important changes, first of all the way
of measuring personality type is changed. 
It uses a strutured approach rather than Carl Jungs projective approach.
The responses to items are finite and therefore can be deduced based on theory.
In contrast to Jung's technique where he used open ended anwsering with word
associations cite:hall1973primer23method.
Then there is the introduction of an extra index used to order function
attitudes cite:carlson1985recent.
Which is either a $J$ for judging (rational in jung terms)
or a $P$ for perceiving (irrational in jung terms).
This dimension indicates together with the $I/E$ dimension which function
attitude is dominant and which is auxilirary.

\cleared
Once completed with the MBTI you'll get charatcter string as outcome,
for example "INTJ".
This label tells you inderectly which of carl jung's functions is dominant,
auxilirary, tetriary and inferior cite:mccaulley2000myers.
In other words it provides a sequence of preferences
cite:website.mbtitypedynamics.
In case of INTJ it would be:
\[N_i > T_e  > F_i > S_e\]
So the most preffered function to be used by someone of type INTJ would be $N_i$,
then $T_e$ and so forth.
These are the same function as Jung used, the MBTI
just imposed an order on them cite:mccaulley2000myers,website.mbtisequence.
How much preference there is for a function is not encoded in MBTI, just an
order of preference.
An ENTJ would be simialar to INTJ but with a different order:
\[T_e > N_i > S_e > F_i\]
With this definition the interplay of the judging/perceiving dimension becomes
more obvious if we look at INTP: \[T_i > N_e > S_i > F_e\]
It's similar to an ENTJ, but the attitudes have flipped.

\cleared
A possible grouping of the sixteen type exists using the middle letters:
\[\{NT, ST, NF, SF\}\]
This grouping goes under the rationale that the first two functions only
differ in either attitude, order or both.

\cleared
Before continuing we would like to say a word about a popular
interpertation of MBTI which is based on Kersey's book "Please understand me",
and later "Please understand me II".
In this interpertation the sixteen types are also placed in general groups
of four but here the $ST$ and $SF$ distinction is replaced by $SJ$ and $SP$
cite:keirsey1998please.
It turns out however that Kersey invented this distinction because
"He thought it made sense to group them this way" cite:whyaretypesdistinct.
In doing this he rejected the work of Jung and also that of cognitive functions.
Which is problematic because the theory he presented then does not make any
thoeretical sense.
Therefore Kersey's MBTI will not be used in this thesis.

\cleared
The MBTI is extremly popular in a subfield called Organizational Developement
(OD) cite:sample2004myers. 
But it has gotton some heavy critism in from the field of psycology.

\cleared
Since MBTI reduces the test scores to type,
it is expected that most of the population would fall into either proposed
dimensions. For example $I$ or $E$.
This is called a bimodal distribution.
However it has been shown that is not the case cite:bess2002bimodal,
but this could be the result of the scores being biderictional
cite:salter2005two.
An extended investigation into weather jungian constructs are truly categorial
however concluded that this was not the case and a continues scale is required
cite:arnau2003jungian.

\cleared
It also fell short on factor analyses and reliability.
With this technique the desired outcome is that there are 4 question clusters
(or factors), one for each dimension.
Secondly these factors should be independent,
a question that influences I/E score should not influence S/N.
Finally we expect the factors to indicate differences between individuals.
Random questions won't do that.
However it turned out the MBTI had more than 4 factors (6), then there were
questions that were in different factors than the majority
and finally there were also some quetions doing no discrimination at all
(not being scored) cite:sipps1985item. 

\cleared
Reliability indicates how often the same result will come out of the test,
for example if you take the mbti a 100 times you may be classified the same
type for 70 times.
Which would be an indication it has a reliablity of arround 70%.
But in psycology another aspect is important,
namely the interval in between which the tests are taken,
if for example two tests produce starkly different results but a long time
has passed between them its not considered a big issue.
However for the MBTI it has been shown that after a period of 5 weeks 50%
of the participants changed in score cite:pittenger1993measuring.
Since Jung basically said that type is decided very early on in life
this result is rather bad cite:hall1973primer106inborn.

*** PPSDQ
\cleared
The PPSDQ keeps basically the same theory as MBTI cite:kier1997new,king1999score,
but uses a different measuring method.
Instead of forced questions it uses a word-pair checklist for
$I/E, S/N$ and $T/F$, and for the $J/P$ self describing sentences are used
cite:melancon1996measurement.
A word pair checklist looks like:

| Word          |   |   |   | Word      |
|---------------+---+---+---+-----------|
| Empathy       | 1 | 2 | 3 | Logic     |
| Dispassionate | 1 | 2 | 3 | Emotional |
The sentence is a statement in which you can agree or disagree. 
This test method is simple but effective.

\cleared
The result of the PPSDQ would look something like: I-30 N-20 T-80 J-60, with
a scale of 0 to 100. To calulate the jungian functions as a probability measure
some math is required. Our subject is $70\%$ of the time introverted and $30\%$ of the 
time extroverted. $60\%$ of the time judging and $40\%$ of the time perceiving.
therefore N_i would be calulated as: 0.7 \times 0.4 \times 0.8 = 0.224 or $22.4\%$.
N_e would be $0.3 \times 0.4 \times 0.8 = 0.096$ etc.
From this you can make a preference sequence or create a mixed strategy.

\cleared
The PPSDQ is measuring the same thing as MBTI but lacks the critisms of MBTI.
The reliability is for example between 90% to 95% with a delay of two weeks.
The internal consistency was also measured which proved to be better than
MBTI but there was still a dependency between S/N and P/J which remains
unexplained cite:kier1997new.
The PPSDQ is internally most consistent of the discussed alternatives
(excluding OCEAN) cite:arnau1999alternative.

*** SL-TDI
\cleared
SL-TDI measures functions by presenting 20 situations and then giving subject
possible actions which corrolate with the functions.
The subjects then have to indicate how likely it is that they would choose that
particular action cite:arnau2000reliability.

\cleared
It becomes rather staight forward to make a function preference of the 
measurement of SL-TDI since the qeustion directly measure the jungian
functions.
A possible personality type therefore would be:
\[ S_i \geq T_i \geq S_e \geq F_e \geq N_i \geq T_e \geq N_e \geq F_i \]
To determine the preference we just used the observed value in the test.
Since every situation offers a choice for each function with a 5 point value
there is no need for normalization.

\cleared
This denotion is much less strict than the MBTI or PPSDQ since it does not force
alternating attitudes or pairing of rational/irrational functions in the
preference.
Therefore the amount of personality types SL-TDI supports drastically exceeds
that of the PPSDQ. In other words, there always exists a mapping from PPSDQ
to SL-TDI, but not always from SL-TDI to PPSDQ.
The reason for doing this is because there is experimental evidence
that there exist personalities outside of the stucture orignally imposed by
MBTI and the subsequent PPSDQ cite:loomis1980testing.


** Comparison of theories
\cleared
To re-iterate, we are interested in a framework that is realistic, and easy to
implement.
The Big Five falls short on the easy to implement,
there is no underlying theoretical framework to support it cite:eysenck1992four,
therefore we cannot base our implementation on anything except our own
interpertation.

\cleared
The MBTI has been criticized a lot from the field of psychology,
but it does have a solid theoretical foundation.
There is some relation between the big five and MBTI cite:furnham1996big.
Therefore its somewhat realistic, but quite easy to implement.

\cleared
Both of the alternatives of MBTI use a continues scale and have a high
correlation with the big five cite:arnau1997measurement.
This means is that they are measuring something which is also measured by the
big five in some way.

\cleared
The PPSDQ is based on the same thoery as MBTI, but with scaled type letters.
To convert the type to function attitudes some extra work has to be done,
namely calulate their respective probabilities.
To decide which function attitude to use some kind of mixed strategy
has to be used.
The PPSDQ is more realistic, but at the cost of being more difficult to
implement.

\cleared
The SL-TDI is even harder to implement than the PPSDQ because the function
attitudes no longer have to alternate.
This either means that functions are independent (thereby rejecting some of Jung's work),
or that they have to work in some kind of combination.
If they work in some kind of combination and we have to following preference:
\[ T_e > T_i > S_i > N_i > F_e > N_e > S_e > F_i\]
We select the first function to work with, but it requires some information now,
what to do?
Select $S_i$, thereby skipping $T_i$, or select $T_i$ and let it decide to
select $S_i$, but this would basially give $T_i$ censorship rights.
This is difficult to anwser therfore it is a lot more difficult to implement
than PPSDQ.
Since SL-TDI drops an assumption, which is shown with experimental evidence
to be false cite:loomis1980testing, we can say SL-TDI's theory is most realistic.
This comes however at the cost of being even more difficult to implement.

\cleared
Therefore our preference for implementation is the following:
\[ \text{MBTI} > \text{PPSDQ} > \text{SL-TDI} > \text{OCEAN} \]

\cleared
There is another hidden reasoning behind this, the work of PPSDQ can built on
that of MBTI, and that of SL-TDI can build on that of PPSDQ.
OCEAN builds on nothing, we'll leave that for future work.

* Artificial personality intelligence
# How do I measure that the persnoality created is in fact in complience with
# the personality I aimed for?
# Can I let the personality take the test somehow?
\drafting
In this chapter we'll discuss the thoery behind intelligent agents,
and reason in favor of this approach.
We'll also compare it with alternatives.


** Agent orientated programming
\drafting
In the literature there is little consensus on what exactly an agent is,
however there is a general consensus that an agent is /autonomous/
cite:wooldridge2009introduction.
To make this more clear we'll use Wooldriges' definition:

#+BEGIN_QUOTE
An /agent/ is a computer system that is /situated/ in some /environment/ and
that is capable of /autonomous action/ in this environment in order to meet its
delegated objectives. -- Wooldridge
#+END_QUOTE

*** Belief desires and intentions
\drafting
\todo[inline]{perhaps talk about bratman?}
\todo[inline]{BDI}
*** Why do this?
\drafting

** Social practices

** BDI + Personality
\drafting
\todo[inline]{content oriented vs process orientated}

\todo[inline]{Personalized bdi architecture}
cite:campos_mabs2009
**** TODO explain how jung functions are programming functions? or data? 


* The serious game
\drafting
There have been several distinct versions of the "comminuate!" game. 
The first version was a web based game, with an extended scenario editor.
cite:jeuring2015demo
However it had some significant flaws, for example each dialog would always
happen the same way if you chose the same answers,
making practicing on it somewhat unrealistic.
This was addressed in the probabilistic reasoner variant.
Which used the concept of /social practices/ to determine probabilistic
responses based on user choices cite:augello2015social.
However the game was still limited too preditermined user choices.
This means the user never has to remember what to do, he can just click some 
choice.
To address this issue the game was extended with an extended version of
AIML cite:weiderveld2016chatbot, called S-AIML cite:augello2016model. 



A specific scenario was created for doctor/patient interaction     
cite:augello2015social.                                            
To train physicians properly /social practices/ are used, which refers to
normal behavior in society.                                        
The game selected these based on a probabilistic model.            
Using this allows students to have multiple runs of a scenario which don't 
follow the same path every time.                                   
The game was later extended to train for specific skills cite:augello2016social,
such as following certain protocols                                
(for example be polite and follow medical standards) and empathy.  

However, since a common complaint against doctors is lack of bed side manner,
it is suggested that doctors should take personality in consideration.
cite:clack2004personality    

The communicate game was created to make doctors able to practice frequently
with talking to patients. \todo{cite this}
To put this in game form is ideal because it allows doctors to practice the
basics without the need for another human patient.
However, the current implementation does not have personality implemented.
This means every virtual patient will always react the same way.
So in the game its always good to be sensitive and polite.
It turns out however the issues most doctors struggle with isn't so much
being sensitive, but rather being sensitive to the people who appreciate it.
cite:clack2004personality

** TODO Existing functionality
\todo[inline]{Existing functionality and design, user interaction etc}
** TODO Existing architecture
\todo[inline]{Existing architecture, how does the trikery work}
cite:augello2016social
** TODO Extending it
\todo[inline]{Proposed Extension, why this extension}
*** TODO Design extension
*** TODO Architecturual changes

* In conclusion
\todo[inline]{Discussion, comparison}
** Future work
\todo[inline]{Depending on the successfulness this chapter becomes smaller and more fine grained}
* References
<<bibliography link>>

bibliographystyle:unsrt
bibliography:refs.bib

