#+TITLE: Adding some personality to serious communication games
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage{natbib}

* TODO Introduction (remove title)

* Personality Theories
The field of psychology has been somewhat active in trying to model human
personality cite:pervin2008handbook. 
Several frameworks have been developed to figure out people's
personality and what this in turn would mean for their lives.
We are interested in two ways in existing personality theories:
1. Accuracy, if a personality thoery does not fit the reality at all it won't
   help anyone in the serious game.
2. Ease of implementation. If the personality theory is too hard (or impossible)
   to implement in the serious game than we can't use it.
Luckily the field of psychology is very interested in the first requirement. 
However the second requirement not so much. Therefore our first job will be
to list existing psychology personality frameworks, and filter out those
that are unfeasible to implement.

** Contending frameworks
In the begining of the 1990's there were many ways to measure psycology that
didn't agree with each other. For example at Berkley alone block used a 2
dimensional ego-resilience and ego-controll method cite:block1980role, whereas
gough measured folk concepts such as self-controll, well-being and tollerance
cite:gough1987california.
Personality researchers hoped that they would be the one to discover a
structure that would then be adopted by other researchers cite:pervin2008handbookp114.

The goal of the big five was not to present a new structure that convinced
others to use it. But rather to provide a taxonomy that all psychologist could
agree upon. Therefore the researchers could keep on exploring there niche, with
their proffered structure, but once they would present their work they could
use the big five to communicate clearly what their research meant without
having to redefining the words every time cite:pervin2008handbookp114..116.

1. MBTI
3. ...

<<bibliography link>>

bibliographystyle:unsrt
bibliography:refs.bib
