#+TITLE: A serious communication game with personalities
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage[obeyFinal, colorinlistoftodos]{todonotes}
#+LaTeX_CLASS: article
#+Options: toc:nil ^:nil 
#+Options: title:nil
#+LATEX_HEADER: \newcommand{\drafting}{\todo[noline, color=gray]{Working draft}}
#+LATEX_HEADER: \newcommand{\toReview}{\todo[noline, color=yellow]{To review}}
#+LATEX_HEADER: \newcommand{\underReview}[1]{\todo[noline, color=olive]{Under review by #1}}
#+LATEX_HEADER: \newcommand{\cleared}{\todo[noline, color=white]{Cleared}}

# Title page

#+LATEX: \input{title}

* Abstract :prelim:
\todo[inline]{abstract}

\newpage
#+TOC: headlines 2

* TODO Introduction here (removing this title)
** TODO keywords (removing this title)

* Related work
\drafting
  To simulate personality in comminucation games there have been already several
works proposed.
Etheredge used the OCEAN personality theory to create argumentative
agents cite:etheredge2016personality.
Although argumentation is not the same as comminucation we can consider the
method used to make the personality.
In this paper a personality model is introduced based on OCEAN.
To move from personality values in OCEAN towards action selection fuzzy logic
is used.
However this has a major disadvantage in that a lot of rules need to be
added to do action selection.
This can make action selection opaque.
It is for example not immediately clear how a higher anxiety will influence
action selection.
Having a lot of rule also make maintenance hard, if for example there is an
unwanted behavior many rules need to be inspected before the change can be made.

In agents with with personalities cocu tried making a complete game based
on MBTI cite:cocu2015agents.
However comminucation was never implemented and personality got reduced to
doing a single action.

Van den bosch also chose to use OCEAN to model characters in a serious
comminucation game cite:van2012characters.
He used a nested probabilistic if else structure to decide on how agents should
interact.
His methodologies had some shortcomings however,
for example a not agreeable person was defined as someone who'd had a high
probability of telling facts about himself.
Which in certain situations could be considered strange,
for example a spy who was captured.
This kind of methodology is called content orientated cite:campos_mabs2009,
the personality, would and should change depending on context.

Campos used the MBTI to create BDI based agents cite:campos_mabs2009.
We will use a more fine grained version of MBTI but his architecture is used,
in which personality will be processed orientated rather than content
orientated.

* Personality Theories
\toReview
The field of psychology has been somewhat active in trying to model human
personality cite:pervin2008handbook. 
Several frameworks have been developed to figure out people's
personality and what this in turn would mean for their lives.
We are interested in two ways in existing personality theories:
1. Accuracy, if a personality thoery does not fit the reality at all it won't
   help anyone in the serious game.
2. Ease of implementation. If the personality theory is too hard (or impossible)
   to implement in the serious game than we can't use it.
Luckily the field of psychology is very interested in the first requirement. 
However the second requirement not so much. Therefore our first job will be
to list existing psychology personality frameworks, and filter out those
that are unfeasible to implement.


** The big five
\toReview
The first framework we'll discuss is called the big five.
This framework was not really invented, but rather discovered trough
lexical analyses cite:tupes1961recurrent.
Although the labels used were different,
they conveyed the same idea as the big five model used now.
The methodology what they used was basically applying manual data mining on a
dictionary and then look at what worked for personality. 
The term big five first coined in 1981 by Goldberg cite:goldberg1981language.
The big five were not big because of their intrinsic greatness, but rather to
emphasize how broad these factors were.

In the begining of the 1990's there were many ways to measure personality that
didn't agree with each other.
For example at Berkley alone block used a 2 dimensional ego-resilience and
ego-controll method cite:block1980role,
whereas gough measured folk concepts such as self-controll, well-being and
tolerance cite:gough1987california.
Personality researchers hoped that they would be the one to discover a structure
that would then be adopted by other researchers cite:pervin2008handbookp114.

The goal of the big five was not to present a new structure that convinced
others to use it.
But rather to provide a taxonomy that all psychologist could agree upon.
Since the big five was so broad, this worked.
Therefore the researchers could keep on exploring there niche,
with their proffered structure,
but once they would present their work they could use the big five to
communicate clearly what their research meant without having to redefining the
words every time cite:pervin2008handbookp114..116.

The big five as in the OCEAN definition has the following units of measurement:
- Openness or originality, if you score high on this you enjoy learning new
  things just for the sake of learning. If you score low then you don't enjoy
  this
- Conciseness, how tidy you are, if you score high the dishes don't stack up
  in the sink.
- Extroversion, a high score indicates you enjoy leading the conversation and
  you'll speak up when you disagree with someone.
- Agreeableness or altruism, a low score would indicate that you don't want to
  share and generally don't trust people.
- Neuroticism or nervousness, a high score indicates that you like to brag and
  get upset when someone is angry at them.

The big five has been extensively tested and the result has been replicated
in multiple studies cite:pervin2008handbookp119.
One can measure his big five score trough a test called the NEO-PI, or the
NEO-FFI. The FFI variant is shorter but less precise cite:costa1992revised.

Although these terms may provide a great taxonomy,
it does not say anything about implementation.
By this we mean that lets say you have a score of 0.8 for Neuroticism,
how does this influence my decision for selecting action $a$ or $b$?
Now you could say, use a mixed strategy where in you choose 80% of the time
the neurotic typical neurotic approach.
Then we need a valuation function $v: A \mapsto i$ where $A$ is an action and
$i \in \mathbb{N}$ to decide which of the two actions is more neurotic.
This still leaves open the question of how this decision interacts with
the other dimensions,
which is non trivial to answer.

** Personality types
\todo{check math of campos/dignum and compare to own}
\toReview
Much of the issues we had with the big five
could be solved by a theoretical foundation of personality types.
To do this we'll look first at the proposed method by the grandfather of 
personality research, Carl Jung.
After which we'll look at a thoeretical evolution proposed by Myers and
Myers-Brigs, which also introduced a structered method of measuring types.
Then we'll discuss some critique's on this method.
*** Jung's theory of psychological types
\toReview
Jung describes several concepts, firstly each person has two attitudes:
/Introversion/ and /extroversion/.
Extroversion means dealing with the outside world and therfore is called
objective (or observable).
Intoversion is the world inside a person, and therefore is subjective,
or private.
Jung argues this may be so private that the consiouness can't even access it.
These attitudes are mutually exclusive,
you can't do introversion and extroversion at the same time.
For example if you're day dreaming you're not doing extroversion.
A person who spends most of his time in the introversion attitude is called
an /introvert/. But he is not totally the one or the other.
Then it should also be noted that the unconsciousness according to Jung is
flipped in attitude. cite:hall1973primer97-98attitude

Then there are four functions that can be combined with the attitudes.
The first two functions are called the /rational functions/
because they act as a method of making judgements.
/Thinking/ is a function that connects ideas with each other to arrive at
generalizations or conclusions. 
/Feeling/ evaluates ideas by determinging if its good or bad, pleasant
or unpleasant, beautifull or ugly.
Note that this is /not/ the same as being emotional,
although you can be emotional and use this function.
The /irrational functions/ are called this becuase they require no reason.
/Sensation/ is sense perception created by the stimulation of the senses,
it can always be rooted to a sense,
such as "I see a balloon" or "I feel hungry".
/Intuition/ is like a sensetion but its not produced by a sense.
Therefore it has no origin in the same way as sensation has,
by which its explained as "just a hunch" or "I feel it in my bones".
cite:hall1973primer98-100functions

To use these functions they have to be combined with attitudes.
Therefore a person will never be of a thinking type,
but rather either a thinking introvert or thinking extrovert.
cite:hall1973primer100-101combo
We can now imagine what this means,
an extroverted thinker will for example make judgement about the real world,
and therefore be more like a scientist,
whereas an introverted thinker will make judgement about ideas in his mind,
and therfore will be an excelent philosopher.

Let $\mathcal{J}$ denote the set of all possible jungian functions such that:
\[ \mathcal{J} = \{ T_e, T_i, F_e, F_i, S_e, S_i, N_e, N_i\}\]
Where
+ $T_e$ stands for extraverted thinking, which is thinking about objects in the
  real world. This is thinking with a goal, a problem to solve,
  or to check weather certain laws are upheld.
+ $T_i$ stands for introverted thinking, this kind of thinking could be called
  deductive, it tries to construct a framework to explain the world.
+ $F_e$ stands for extraverted feeling, where objective or external criteria
  is used to judge, for example something is beautifull or ugly.
  Established standards may be used to decide this and therefore its a
  conservative function. Decisions are based on interpersonal and cultural values.
+ $F_i$ stands for introverted feeling, decisions based on personal values.
+ $S_e$ stands for extroverted sensing, Act on concrete data from the here and
  now. Then lets it go.
+ $S_i$ stands for introverted sensing, acts on concrete data from memories and
  passed experience.
+ $N_e$ stands for extraverted intuition, try to find possibilities in every
  situation.
+ $N_i$ stands for introverted intuition. Looks new possibilities in ideas.
# TODO revise this

*** MBTI
\toReview
The meyer brigs type indicator is based upon Carl Jung's theory of personality
types.
However it brings two important changes, first of all the way
of measuring personality type is changed. 
First of all it uses a strutured approach rather than Carl Jungs projective
approach.
The responses to items are finite and therefore can be deduced based on theory.
Jung used open ended anwsering with word associations for example cite:hall1973primer23method.
Then there is the introduction of the fourth letter to the type
cite:carlson1985recent.
Which is either a $J$ for judging (rational in jung terms)
or a $P$ for perceiving (irrational in jung terms).
This dimension indicates together with the $I/E$ dimension which function is
dominant and which is auxilirary which we'll see later.
However once the assesment is complete the scores are reduced to a type.

Once completed with the MBTI you'll get a type as outcome, for example "INTJ".
This label tells you inderectly which of carl jung's functions is dominant,
auxilirary, tetriary and inferior cite:mccaulley2000myers.
In other words it provides a sequence of preferences
cite:website.mbtitypedynamics.
In case of INTJ it would be: \[N_i > T_e  > F_i > S_e\]
So the most preffered function to be used by someone of type INTJ would be $N_i$,
then $T_e$ and so forth.
In this case $N_i$ means introverted iNtuition cite:website.mbtisequence. 
These are the same function as Jung used, the MBTI
just imposed an order on them cite:mccaulley2000myers.
How much preference there is for a function is not encoded in MBTI, just an
order of preference.
An ENTJ would be simialar to INTJ but with the order a little different:
\[T_e > N_i > S_e > F_i\]
With this definition the interplay of the judging/perceiving dimension becomes
more obvious if we look at INTP: \[T_i > N_e > S_i > F_e\]
It's similar to an ENTJ, but the attitudes have flipped.

A possible grouping of the sixteen type exists using the middle letters:
\[\{NT, ST, NF, SF\}\]
This grouping goes under the rationale that the first two functions only
differ in either attitude, order or both.

Before continuing we would like to say a word about a popular
interpertation of MBTI which is based on Kersey's book "Please understand me",
and later "Please understand me II".
In this interpertation the sixteen types are also placed in general groups
of four but here the $ST$ and $SF$ distinction is replaced by $SJ$ and $SP$
cite:keirsey1998please.
It turns out however that Kersey invented this distinction because
"He thought it made sense to group them this way" cite:whyaretypesdistinct.
In doing this he rejected the work of Jung and also that of cognitive functions.
Which is problematic because the theory he presented then does not make any
thoeretical sense.
Therefore Kersey's MBTI will not be used in this thesis.

The MBTI is extremly popular in a subfield called Organizational Developement
(OD) cite:sample2004myers. 
But it has gotton some heavy critism in from the field of psycology.

MBTI expects if someone that is of type $I$ falls clearly into
the $I$ category,
therfore a bimodal distribution is expected.
This means that most people should eiter clearly fall into $I$ or $E$. 
however it has been shown that is not the case cite:bess2002bimodal,
but this could be the result of the scores being biderictional
cite:salter2005two.
An extended investigation into weather jungian constructs are truly categorial
however concluded that this was not the case and a continues scale is required
cite:arnau2003jungian.

It also fell short on factor analyses and reliability.
Factor analyses tries to deduce based on observerd variables potential
simpler un-observerd variables.
With this technique the desired outcome is that there are 4 question clusters
(or factors), one for each dimension.
Secondly these factors should be independent,
a question that influences I/E score should not influence S/N.
Finally we expect the factors to indicate differences between individuals.
Random questions won't do that.
However it turned out the MBTI had more than 4 factors (6), then there were
questions that were in different factors than the majority
and finally there were also some quetions doing no discrimination at all
(not being scored). cite:sipps1985item

Reliability indicates how often the same result will come out of the test,
for example if you take the mbti a 100 times you may be classified the same
type for 70 times.
Which would be an indication it has a reliablity of arround 70%.
But in psycology another aspect is important,
namely the interval in between which the tests are taken,
if for example two tests produce starkly different results but a lot of time
has passed between them its not considered a big issue.
However for the MBTI it has been shown that after a period of 5 weeks 50%
of the participants changed in score cite:pittenger1993measuring.

*** PPSDQ
\toReview
The PPSDQ keeps basically the same theory as MBTI cite:kier1997new,king1999score,
but uses a different measuring method.
Instead of forced questions it uses a word-pair checklist for
$I/E, S/N$ and $T/F$, and for the $J/P$ self describing sentences are used
cite:melancon1996measurement.
A word pair checklist looks like:

| Word          |   |   |   | Word      |
|---------------+---+---+---+-----------|
| Empathy       | 1 | 2 | 3 | Logic     |
| Dispassionate | 1 | 2 | 3 | Emotional |
The sentence is a statement in which you can agree or disagree. 
This test method is simple but effective.

The result of the PPSDQ would look something like: I-30 N-20 T-80 J-60, with
a scale of 0 to 100. To calulate the jungian functions as a probability measure
some math is required. Our subject is $70\%$ of the time introverted and $30\%$ of the 
time extroverted. $60\%$ of the time judging and $40\%$ of the time perceiving.
therefore N_i would be calulated as: 0.7 \times 0.4 \times 0.8 = 0.224 or $22.4\%$.
N_e would be $0.3 \times 0.4 \times 0.8 = 0.096$ etc.
From this you can make a preference sequence or create a mixed strategy.

The PPSDQ is measuring the same thing as MBTI but lacks the critisms of MBTI.
The PPSDQ is internally most consistent of the discussed alternatives
(excluding OCEAN) cite:arnau1999alternative.
*** SL-TDI
\toReview
SL-TDI measures functions by presenting 20 situations and then giving subject
possible actions which corrolate with the functions.
The subjects then have to indicate how likely it is that they would choose that
particular action cite:arnau2000reliability.

It becomes rather staight forward to make a function preference of the 
measurement of SL-TDI since the qeustion directly measure the jungian
functions.
A possible personality type therefore would be:

\[ S_i \geq T_i \geq S_e \geq F_e \geq N_i \geq T_e \geq N_e \geq F_i \]

Where $o$ is a function $ f \in \mathcal{J}, i \in \mathbb{I}, o: f \mapsto i$
in which $i$ is the type mode score of $f$.

This denotion is much less strict than the MBTI or PPSDQ since it does not force
alternating attitudes or pairing of rational/irrational functions.
Therefore the amount of personality types SL-TDI supports drastically exceeds
that of the PPSDQ. In other words, there always exists a mapping from PPSDQ
to SL-TDI, but not always from SL-TDI to PPSDQ.
The reason for doing this is because there is experimental evidence
that there exist personalities outside of the stucture orignally imposed by
MBTI and the subsequent PPSDQ cite:loomis1980testing.


** Comparison of theories
\toReview
To re-iterate, we are interested in a framework that is realistic, and easy to
implement.
The Big Five falls short on the easy to implement,
there is no underlying theoretical framework to support it cite:eysenck1992four,
therefore we cannot base our implementation on anything except our own
interpertation.

The MBTI has been criticized a lot from the field of psychology,
but it does have a solid theoretical foundation.
There is some relation between the big five and MBTI cite:furnham1996big.
Therefore its somewhat realistic, but quite easy to implement.

Both of the alternatives of MBTI use a continues scale and have a high
correlation with the big five cite:arnau1997measurement.
This means is that they are measuring something which is also measured by the
big five in some way.

The PPSDQ is based on the same thoery as MBTI, but with scaled type letters.
To convert the type to function attitudes some extra work has to be done,
namely calulate their respective probabilities.
To decide which function attitude to use some kind of mixed strategy
has to be used.
The PPSDQ is more realistic, but at the cost of being more difficult to
implement.

The SL-TDI is even harder to implement than the PPSDQ because the function
attitudes no longer have to alternate.
This means that function attidues have to work in any combination,
for example a function pair of $T_e, T_i$ is impossible in both PPSDQ and MBTI.
Since SL-TDI drops an assumption, which is shown with experimental evidence
to be false cite:loomis1980testing, we can say SL-TDI's theory is most realistic.
This comes however at the cost of being even more difficult to implement.

Therefore our preference for implementation is the following:

\[ \text{MBTI} > \text{PPSDQ} > \text{SL-TDI} > \text{OCEAN} \]

There is another hidden reasoning behind this, the work of PPSDQ can built on
that of MBTI, and that of SL-TDI can build on that of PPSDQ.
OCEAN builds on nothing, we'll leave that for future work.
\todo[inline]{content oriented vs process orientated}


** Communication in framework
\drafting
Most of the research on comminucation in this chapter is based on MBTI,
it can to some extend also be applied to the PPSDQ and SL-TDI since they are 
based on the same theoretical construct.
However it should be noted that its not a one to one mapping.
Here we discuss research into communication based on this framework.

* Agent orientated programming
\todo[inline]{perhaps talk about bratman?}
\todo[inline]{BDI}
\todo[inline]{Personalized bdi architecture}
cite:campos_mabs2009
* The communicate game
cite:augello2015social
** TODO Existing functionality
\todo[inline]{Existing functionality, user interaction etc}
** TODO Existing architecture
\todo[inline]{Existing architecture, how does the trikery work}
cite:campos_mabs2016
** TODO Extending it
\todo[inline]{Proposed Extension, why this extension}

* Conclusion
\todo[inline]{Discussion}
** Future work
\todo[inline]{Depending on the successfulness this chapter becomes smaller and more fine grained}
* Attachments
<<bibliography link>>

bibliographystyle:unsrt
bibliography:refs.bib

